"""add batch source and device unique constraint

Revision ID: 43bc63841421
Revises: 86e423b88f70
Create Date: 2026-06-18 11:10:08.442296

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '43bc63841421'
down_revision: str | None = '86e423b88f70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('source', sa.Text(), nullable=True))
    op.execute("UPDATE batches SET source = 'http' WHERE source IS NULL")
    op.alter_column('batches', 'source', existing_type=sa.Text(), nullable=False)
    op.create_unique_constraint('uq_device_batch_sparam', 'devices', ['batch_id', 's_param_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_batch_sparam', 'devices', type_='unique')
    op.drop_column('batches', 'source')
    # ### end Alembic commands ###
