"""add batch deembed_method

Revision ID: 70da8915313e
Revises: 2026_06_10_140500
Create Date: 2026-06-10 17:46:31.382917

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '70da8915313e'
down_revision: str | None = '2026_06_10_140500'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('deembed_method', sa.Text(), nullable=False))
    op.drop_index(op.f('idx_dev_filename_prefix'), table_name='devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('idx_dev_filename_prefix'), 'devices',
        [sa.literal_column('"left"(original_filename, 50)')], unique=False,
    )
    op.drop_column('batches', 'deembed_method')
    # ### end Alembic commands ###
