"""add device s_param_port

Revision ID: 78bd1c93213e
Revises: 43bc63841421
Create Date: 2026-06-02 09:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78bd1c93213e'
down_revision: Union[str, None] = '43bc63841421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'devices',
        sa.Column('s_param_port', sa.Text(), server_default='S11', nullable=False),
    )
    op.drop_constraint('uq_device_batch_sparam', 'devices', type_='unique')
    op.create_unique_constraint(
        'uq_device_batch_sparam_port',
        'devices',
        ['batch_id', 's_param_path', 's_param_port'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_batch_sparam_port', 'devices', type_='unique')
    op.create_unique_constraint(
        'uq_device_batch_sparam', 'devices', ['batch_id', 's_param_path']
    )
    op.drop_column('devices', 's_param_port')
    # ### end Alembic commands ###
